const orders = [{
	orderCode: "123456796354",
	paymentState: 0,
	total: 2,
	money: 1598,
	lists: [{
			order_id: 0,
			shopName: "店铺名称",
			commodityImg: "/static/img/comment/comment-img.jpg",
			commoditytitle: "北欧风格布艺转角沙发",
			commodityAttr: "棕色/760*589*125mm/不安装",
			commodityPrice: 799.00,
			commodityNum: 1,
			distributionMode: "上门安装",
			invoice: "商品明细",
			remarks: "无",
			installationCost: "100",
			total: 1,
			money: 899,
		},
		{
			order_id: 0,
			shopName: "店铺名称",
			commodityImg: "/static/img/comment/comment-img.jpg",
			commoditytitle: "北欧风格布艺转角沙发",
			commodityAttr: "棕色/760*589*125mm/不安装",
			commodityPrice: 799.00,
			commodityNum: 1,
			distributionMode: "上门安装",
			invoice: "商品明细",
			remarks: "无",
			installationCost: "100",
			total: 1,
			money: 899,
		},
	]
}, {
	orderCode: "123456796354",
	paymentState: 1,
	total: 2,
	money: 1598,
	lists: [{
			order_id: 0,
			shopName: "店铺名称",
			commodityImg: "/static/img/comment/comment-img.jpg",
			commoditytitle: "北欧风格布艺转角沙发",
			commodityAttr: "棕色/760*589*125mm/不安装",
			commodityPrice: 799.00,
			commodityNum: 1,
			distributionMode: "上门安装",
			invoice: "商品明细",
			remarks: "无",
			installationCost: "100",
			total: 1,
			money: 899,
		},
		{
			order_id: 0,
			shopName: "店铺名称",
			commodityImg: "/static/img/comment/comment-img.jpg",
			commoditytitle: "北欧风格布艺转角沙发",
			commodityAttr: "棕色/760*589*125mm/不安装",
			commodityPrice: 799.00,
			commodityNum: 1,
			distributionMode: "上门安装",
			invoice: "商品明细",
			remarks: "无",
			installationCost: "100",
			total: 1,
			money: 899,
		},
	]
}, {
	orderCode: "123456796354",
	paymentState: 4,
	total: 2,
	money: 1598,
	lists: [{
			order_id: 0,
			shopName: "店铺名称",
			commodityImg: "/static/img/comment/comment-img.jpg",
			commoditytitle: "北欧风格布艺转角沙发",
			commodityAttr: "棕色/760*589*125mm/不安装",
			commodityPrice: 799.00,
			commodityNum: 1,
			distributionMode: "上门安装",
			invoice: "商品明细",
			remarks: "无",
			installationCost: "100",
			total: 1,
			money: 899,
		},
		{
			order_id: 0,
			shopName: "店铺名称",
			commodityImg: "/static/img/comment/comment-img.jpg",
			commoditytitle: "北欧风格布艺转角沙发",
			commodityAttr: "棕色/760*589*125mm/不安装",
			commodityPrice: 799.00,
			commodityNum: 1,
			distributionMode: "上门安装",
			invoice: "商品明细",
			remarks: "无",
			installationCost: "100",
			total: 1,
			money: 899,
		},
	]
}, {
	orderCode: "123456796354",
	paymentState: 5,
	total: 2,
	money: 1598,
	lists: [{
			order_id: 0,
			shopName: "店铺名称",
			commodityImg: "/static/img/comment/comment-img.jpg",
			commoditytitle: "北欧风格布艺转角沙发",
			commodityAttr: "棕色/760*589*125mm/不安装",
			commodityPrice: 799.00,
			commodityNum: 1,
			distributionMode: "上门安装",
			invoice: "商品明细",
			remarks: "无",
			installationCost: "100",
			total: 1,
			money: 899,
		},
		{
			order_id: 0,
			shopName: "店铺名称",
			commodityImg: "/static/img/comment/comment-img.jpg",
			commoditytitle: "北欧风格布艺转角沙发",
			commodityAttr: "棕色/760*589*125mm/不安装",
			commodityPrice: 799.00,
			commodityNum: 1,
			distributionMode: "上门安装",
			invoice: "商品明细",
			remarks: "无",
			installationCost: "100",
			total: 1,
			money: 899,
		},
	]
}, {
	orderCode: "123456796354",
	paymentState: 6,
	total: 2,
	money: 1598,
	lists: [{
			order_id: 0,
			shopName: "店铺名称",
			commodityImg: "/static/img/comment/comment-img.jpg",
			commoditytitle: "北欧风格布艺转角沙发",
			commodityAttr: "棕色/760*589*125mm/不安装",
			commodityPrice: 799.00,
			commodityNum: 1,
			distributionMode: "上门安装",
			invoice: "商品明细",
			remarks: "无",
			installationCost: "100",
			total: 1,
			money: 899,
		},
		{
			order_id: 0,
			shopName: "店铺名称",
			commodityImg: "/static/img/comment/comment-img.jpg",
			commoditytitle: "北欧风格布艺转角沙发",
			commodityAttr: "棕色/760*589*125mm/不安装",
			commodityPrice: 799.00,
			commodityNum: 1,
			distributionMode: "上门安装",
			invoice: "商品明细",
			remarks: "无",
			installationCost: "100",
			total: 1,
			money: 899,
		},
	]
}]
const paymentsItem = [{
	orderCode: "123456796354",
	paymentState: 0,
	total: 2,
	money: 1598,
	lists: [{
		order_id: 2,
		shopName: "店铺名称",
		commodityImg: "/static/img/comment/comment-img.jpg",
		commoditytitle: "北欧风格布艺转角沙发",
		commodityAttr: "棕色/760*589*125mm/不安装",
		commodityPrice: 799.00,
		commodityNum: 1,
		distributionMode: "上门安装",
		invoice: "商品明细",
		remarks: "无",
		installationCost: "100",
		total: 1,
		money: 899
	}, {
		order_id: 2,
		shopName: "店铺名称",
		commodityImg: "/static/img/comment/comment-img.jpg",
		commoditytitle: "北欧风格布艺转角沙发",
		commodityAttr: "棕色/760*589*125mm/不安装",
		commodityPrice: 799.00,
		commodityNum: 1,
		distributionMode: "上门安装",
		invoice: "商品明细",
		remarks: "无",
		installationCost: "100",
		total: 1,
		money: 899
	}]
}]
const receiptsItem = [{
	orderCode: "123456796354",
	paymentState: 2,
	total: 2,
	money: 1598,
	lists: [{
		order_id: 3,
		shopName: "店铺名称",
		commodityImg: "/static/img/comment/comment-img.jpg",
		commoditytitle: "北欧风格布艺转角沙发",
		commodityAttr: "棕色/760*589*125mm/不安装",
		commodityPrice: 799.00,
		commodityNum: 1,
		distributionMode: "上门安装",
		invoice: "商品明细",
		remarks: "无",
		installationCost: "100",
		total: 1,
		money: 899
	}, {
		order_id: 3,
		shopName: "店铺名称",
		commodityImg: "/static/img/comment/comment-img.jpg",
		commoditytitle: "北欧风格布艺转角沙发",
		commodityAttr: "棕色/760*589*125mm/不安装",
		commodityPrice: 799.00,
		commodityNum: 1,
		distributionMode: "上门安装",
		invoice: "商品明细",
		remarks: "无",
		installationCost: "100",
		total: 1,
		money: 899
	}]
}, {
	orderCode: "123456796354",
	paymentState: 1,
	total: 2,
	money: 1598,
	lists: [{
		order_id: 3,
		shopName: "店铺名称",
		commodityImg: "/static/img/comment/comment-img.jpg",
		commoditytitle: "北欧风格布艺转角沙发",
		commodityAttr: "棕色/760*589*125mm/不安装",
		commodityPrice: 799.00,
		commodityNum: 1,
		distributionMode: "上门安装",
		invoice: "商品明细",
		remarks: "无",
		installationCost: "100",
		total: 1,
		money: 899
	}, {
		order_id: 3,
		shopName: "店铺名称",
		commodityImg: "/static/img/comment/comment-img.jpg",
		commoditytitle: "北欧风格布艺转角沙发",
		commodityAttr: "棕色/760*589*125mm/不安装",
		commodityPrice: 799.00,
		commodityNum: 1,
		distributionMode: "上门安装",
		invoice: "商品明细",
		remarks: "无",
		installationCost: "100",
		total: 1,
		money: 899
	}]
}]
const returnsItem = [{
	orderCode: "123456796354",
	paymentState: 5,
	total: 2,
	money: 1598,
	lists: [{
		order_id: 4,
		shopName: "店铺名称",
		commodityImg: "/static/img/comment/comment-img.jpg",
		commoditytitle: "北欧风格布艺转角沙发",
		commodityAttr: "棕色/760*589*125mm/不安装",
		commodityPrice: 799.00,
		commodityNum: 1,
		distributionMode: "上门安装",
		invoice: "商品明细",
		remarks: "无",
		installationCost: "100",
		total: 1,
		money: 899
	}, {
		order_id: 4,
		shopName: "店铺名称",
		commodityImg: "/static/img/comment/comment-img.jpg",
		commoditytitle: "北欧风格布艺转角沙发",
		commodityAttr: "棕色/760*589*125mm/不安装",
		commodityPrice: 799.00,
		commodityNum: 1,
		distributionMode: "上门安装",
		invoice: "商品明细",
		remarks: "无",
		installationCost: "100",
		total: 1,
		money: 899
	}]
}]
const completesItem = [{
	orderCode: "123456796354",
	paymentState: 6,
	total: 2,
	money: 1598,
	lists: [{
		order_id: 5,
		shopName: "店铺名称",
		commodityImg: "/static/img/comment/comment-img.jpg",
		commoditytitle: "北欧风格布艺转角沙发",
		commodityAttr: "棕色/760*589*125mm/不安装",
		commodityPrice: 799.00,
		commodityNum: 1,
		distributionMode: "上门安装",
		invoice: "商品明细",
		remarks: "无",
		installationCost: "100",
		total: 1,
		money: 899
	}, {
		order_id: 5,
		shopName: "店铺名称",
		commodityImg: "/static/img/comment/comment-img.jpg",
		commoditytitle: "北欧风格布艺转角沙发",
		commodityAttr: "棕色/760*589*125mm/不安装",
		commodityPrice: 799.00,
		commodityNum: 1,
		distributionMode: "上门安装",
		invoice: "商品明细",
		remarks: "无",
		installationCost: "100",
		total: 1,
		money: 899
	}]
}]

export default {
	orders,
	paymentsItem,
	receiptsItem,
	returnsItem,
	completesItem
}
